"""Session-wide containment for scratch directories.

WHY THIS EXISTS. Nineteen call sites across this suite build their workspaces
with `tempfile.mkdtemp()`, and `mkdtemp` never cleans up -- that is its
contract. Many of those workspaces are whole repository copies: `faithful_copy`
alone writes every tracked file plus a real `.git`.

Nothing removed them. A single full run left thousands of directories behind,
they accumulated across runs, and the disk reached zero bytes mid-suite. Three
consecutive full-suite runs died that way, each reporting a success exit code
because the failure was in `tail` and `git`, not in pytest. 8,379 abandoned
workspaces were removed by hand afterwards, holding 7.5 GB.

The fix is one place rather than nineteen: `tempfile.tempdir` is repointed at a
per-session directory, so every `mkdtemp` in the suite -- including call sites
nobody has written yet -- lands inside it, and the whole thing is removed when
the session ends.

Not left to pytest's own retention. `tmp_path_factory` keeps the last three
runs, which for a suite that copies the repository thousands of times is still
tens of gigabytes. It is deleted outright.
"""

from __future__ import annotations

import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]


def _worktree_state() -> str:
    """What git says about the working tree, or "" when git cannot answer."""
    try:
        completed = subprocess.run(  # noqa: S603
            ["git", "status", "--porcelain"],
            cwd=ROOT, capture_output=True, text=True, encoding="utf-8",
            errors="replace", timeout=120, check=False,
        )
    except OSError:
        return ""
    return completed.stdout if completed.returncode == 0 else ""


@pytest.fixture(scope="session", autouse=True)
def _contained_scratch(tmp_path_factory: pytest.TempPathFactory):
    """Point `tempfile` at a directory this session owns, and remove it after.

    `autouse` and session-scoped because the leak is a property of the suite,
    not of any test that has to remember to opt in. A test that must keep a
    workspace beyond the session should say so explicitly rather than rely on
    the absence of cleanup.
    """
    original = tempfile.tempdir
    scratch = Path(tmp_path_factory.mktemp("scratch"))
    tempfile.tempdir = str(scratch)
    try:
        yield scratch
    finally:
        tempfile.tempdir = original
        # `ignore_errors` because a workspace holding a still-open handle must
        # not fail the run: the point is to reclaim space, and a directory that
        # survives one session is a leak, not a broken test.
        shutil.rmtree(scratch, ignore_errors=True)


@pytest.fixture(scope="session", autouse=True)
def _governed_tree_is_left_as_found():
    """The suite must not leave the governed tree modified.

    Several tests mutate real tracked files and restore them in `finally` --
    which holds right up until a run does not reach the restore. One did not:
    forged `authenticated_inspections` records survived an interrupted run in
    `test_artifact_authority.py` and were committed, so a governed artifact in
    this repository asserted three authenticated inspections that never
    happened, and `observe_governance_integrity` reported COMPROMISED because
    of it. Nobody noticed until the file was regenerated by accident.

    Those particular tests now work in copies. This catches the next one --
    including modules not yet written, and including the semantic-binding suite,
    which still mutates the contracts in place under a restoring fixture.

    A loud failure at session end is the point. Silent corruption of a governed
    artifact is the failure mode that actually happened, and it is the one a
    `finally` cannot prevent.
    """
    before = _worktree_state()
    yield
    after = _worktree_state()
    if not before and not after:
        return  # git could not answer; absence of an answer is not a pass here

    introduced = sorted(set(after.splitlines()) - set(before.splitlines()))
    assert introduced == [], (
        "the test suite left the governed tree modified:\n  "
        + "\n  ".join(introduced)
        + "\n\nA test mutated a tracked file and did not restore it. Restore it "
        "with `git checkout --` after checking the diff, and move that test's "
        "workspace into a copy: a `finally` does not run when a process dies, "
        "and this exact failure has already put forged attestation records into "
        "a commit."
    )
