"""Why the strict path refused, told apart from the mere fact that it refused.

The strict backend must fail closed when no human approval exists. Two tests
assert that, and both used to assert it by naming ONE diagnostic string:

    tests/test_execution_mode_truth.py   assert "CONTRACT_INVALID" in reason
    tests/test_approval_reachability.py  assert "AN_APPROVAL_RECORD_MISSING" ...

Both of those appear only once `.nornyx/runtime/nornyx.agentic_network.lock`
exists. That path is gitignored, and `scripts/prepare_runtime.py` refuses to
write it without a human approval -- measured: rc=2, the report names
AN_APPROVAL_RECORD_MISSING / APPROVAL_EVIDENCE_MISSING / EVIDENCE_REQUIRED_MISSING,
and the only file it leaves behind is `preparation-report.json`. So no reader
can produce the lock, every clean checkout refuses one step earlier with
RUNTIME_LOCK_MISSING, and both tests failed for everyone but their author.

The first repair widened one of them to a SET of codes including
RUNTIME_LOCK_MISSING, and left the other -- one grep away -- untouched. A
review found the survivor, and a second review found that the widened set was
too loose anyway: "the lock file is not there" is satisfied by someone deleting
it, which says nothing about human authority. Two trees with identical
contracts and identical (absent) approval state gave different codes purely
because one had a lock.

So the depth is not what is asserted. The CAUSE is:

    no human approval  ->  prepare_runtime refuses  ->  no lock
                       ->  the boundary cannot load the authorizer

When the refusal names the approval directly, that IS the cause. When it names
only the absent lock, the absence is evidence of nothing until the tree is
asked whether a human approval exists -- and this repository records that in a
tracked artifact it regenerates on every commit. If an approval were granted
and the lock merely deleted, the check below fails, which is correct: the
refusal would then not be evidence of absent human authority.
"""

from __future__ import annotations

import json
from pathlib import Path

#: The refusal names the absent approval itself.
APPROVAL_NAMED_DIRECTLY = frozenset({
    "AN_APPROVAL_RECORD_MISSING",
    "APPROVAL_EVIDENCE_MISSING",
    "EVIDENCE_REQUIRED_MISSING",
})

#: The refusal names only the consequence: the authorizer never loaded because
#: the lock is absent. Admissible ONLY with the cause established below.
LOCK_ABSENT = "RUNTIME_LOCK_MISSING"

APPROVAL_RECORD = ".nornyx/contracts/evidence/architecture_approval_record.json"
RUNTIME_LOCK = ".nornyx/runtime/nornyx.agentic_network.lock"


class RefusalNotFromAbsentApproval(AssertionError):
    """The strict path refused, but not because human authority is absent."""


def human_approval_granted(root: Path) -> bool:
    """Read the repository's own record of whether a human approved anything.

    Regenerated by `scripts/refresh_governance_evidence.py` on every commit and
    tracked, so it is a fact about the checkout rather than about the machine.
    A record that is missing or unreadable is NOT read as "granted" -- the
    question here is whether authority is present, and absence of the record is
    absence of authority.
    """
    location = root / APPROVAL_RECORD
    try:
        payload = json.loads(location.read_bytes().decode("utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return False
    if not isinstance(payload, dict):
        return False
    return "granted" in {payload.get("approval"), payload.get("production_approval")}


def assert_absent_human_authority(reason: str, root: Path) -> str:
    """Refuse anything that is not the absent human approval. Return the depth.

    Deliberately NOT `any(code in reason for code in SET)`. That form admits a
    deleted lock, and a control that admits a deleted lock cannot tell the
    honest state of this repository from a broken install.
    """
    named = sorted(code for code in APPROVAL_NAMED_DIRECTLY if code in reason)
    if named:
        return named[0]

    if LOCK_ABSENT not in reason:
        raise RefusalNotFromAbsentApproval(
            "the governed path failed for a reason outside absent human "
            "authority. Expected one of "
            + str(sorted(APPROVAL_NAMED_DIRECTLY | {LOCK_ABSENT}))
            + " -- got: " + reason
        )

    # The lock is absent. That is a consequence, not a cause. Establish the
    # cause from the tree rather than assuming it.
    if human_approval_granted(root):
        raise RefusalNotFromAbsentApproval(
            "the refusal names only the absent runtime lock, but this tree "
            "records a GRANTED human approval, so the lock is missing for some "
            "other reason and this refusal is not evidence about human "
            "authority: " + reason
        )
    if (root / RUNTIME_LOCK).exists():
        raise RefusalNotFromAbsentApproval(
            "the refusal names the runtime lock as absent while it is present "
            "on disk, so the diagnostic and the tree disagree: " + reason
        )
    return LOCK_ABSENT
