"""The baseline gate must fail on any diagnostic that is not the approval gap."""

from __future__ import annotations

import json
import shutil
import subprocess
import sys
from datetime import datetime
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
SCRIPT = "scripts/check_pre_approval_baseline.py"
CONTRACTS = Path(".nornyx/contracts")
CONTRACT_FILES = (
    CONTRACTS / "runtime_network.nyx",
    CONTRACTS / "architecture_governance.nyx",
)


def _tree(tmp_path: Path) -> Path:
    workspace = tmp_path / "repo"
    # The whole toolchain: a hand-listed subset goes stale as soon as the
    # tooling grows a module, and the import error that follows looks like the
    # refusal under test rather than a broken fixture.
    shutil.copytree(
        ROOT / "scripts",
        workspace / "scripts",
        ignore=shutil.ignore_patterns("__pycache__", "*.pyc"),
    )
    shutil.copy2(ROOT / "pyproject.toml", workspace / "pyproject.toml")
    # .gitignore is itself a governed path, and the real repository relies on
    # it to keep bytecode out of the tree. Without it the tool writes
    # scripts/__pycache__ on first run and the governed-tree gate correctly
    # refuses the workspace as dirty.
    shutil.copy2(ROOT / ".gitignore", workspace / ".gitignore")
    # Derived from the scope rather than listed. This fixture, and six others,
    # each named the scope's contents by hand and each broke when the scope
    # gained a required file -- twice now. SUBJECT_SCOPE_INCOMPLETE is the scope
    # correctly refusing to compute a smaller subject and call it verified, so
    # the fixtures were wrong both times, not the control.
    import sys as _sys

    _sys.path.insert(0, str(ROOT / "tests"))
    from governed_workspace import copy_governed_workspace  # noqa: PLC0415

    copy_governed_workspace(workspace)
    if not (workspace / CONTRACTS).exists():
        shutil.copytree(ROOT / CONTRACTS, workspace / CONTRACTS)
    # --regenerate shells out to the refresh script, which needs the package and
    # a real revision to bind evidence to.
    shutil.copytree(ROOT / "src", workspace / "src", dirs_exist_ok=True)
    for command in (
        ["init", "-q"],
        ["config", "user.email", "fixture@example.invalid"],
        ["config", "user.name", "fixture"],
        ["add", "-A"],
        ["commit", "-qm", "fixture baseline"],
    ):
        subprocess.run(["git", *command], cwd=workspace, check=True, capture_output=True)
    return workspace


def _run(workspace: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, SCRIPT],
        cwd=workspace,
        capture_output=True,
        text=True,
    )


@pytest.mark.skipif(shutil.which("nornyx") is None, reason="nornyx CLI is not installed")
def test_contracts_fail_only_for_want_of_human_approval(tmp_path: Path):
    """State-agnostic: each contract either validates or is approval-blocked.

    This holds before a human approval exists and after one is supplied, so the
    gate does not have to be rewritten when an approval lands or expires. What it
    never tolerates is a diagnostic that is not about the approval.
    """
    completed = _run(_tree(tmp_path))
    assert completed.returncode == 0, completed.stdout + completed.stderr
    report = json.loads(completed.stdout)
    assert report["status"] == "pass"
    for contract in report["contracts"]:
        assert contract["validates"] or contract["approval_blocked"], contract
        assert contract["unexpected_diagnostics"] == [], contract


def _inside_committed_window() -> str:
    """An instant the committed machine evidence is actually valid at.

    Read from the evidence rather than written as a literal, so the case cannot
    drift out of its own window: the evidence has to have been generated by
    then, and must not have expired.
    """
    generated: list[str] = []
    expires: list[str] = []
    for contract in CONTRACT_FILES:
        document = yaml.safe_load((ROOT / contract).read_text(encoding="utf-8"))
        for record in document.get("governance_evidence", {}).get("records", []):
            if record.get("generated_at"):
                generated.append(record["generated_at"])
            if record.get("expires_at"):
                expires.append(record["expires_at"])

    latest_start = datetime.fromisoformat(max(generated).replace("Z", "+00:00"))
    earliest_end = datetime.fromisoformat(min(expires).replace("Z", "+00:00"))
    assert latest_start < earliest_end, "the committed evidence has no common window"
    midpoint = latest_start + (earliest_end - latest_start) / 2
    return midpoint.strftime("%Y-%m-%dT%H:%M:%SZ")


def _nornyx_check(contract: Path, *, as_of: str, cwd: Path) -> tuple[int, str]:
    completed = subprocess.run(
        [shutil.which("nornyx") or "nornyx", "check", str(contract), "--as-of", as_of],
        cwd=cwd,
        capture_output=True,
        text=True,
    )
    return completed.returncode, completed.stdout + completed.stderr


@pytest.mark.skipif(shutil.which("nornyx") is None, reason="nornyx CLI is not installed")
@pytest.mark.parametrize(
    ("as_of", "regenerate"),
    [
        # Inside the committed machine-evidence window: healthy as committed.
        # Derived from that evidence rather than written as a literal. This case
        # was pinned to an absolute instant, which held only while the committed
        # evidence happened to predate it; regenerating the evidence later the
        # same day put `generated_at` *after* the instant under test and the
        # case failed on a freshness diagnostic that says nothing about
        # approvals.
        (None, False),
        # Beyond it: healthy after the documented review-time regeneration.
        ("2030-01-01T00:00:00Z", True),
        ("2045-12-31T23:59:59Z", True),
    ],
)
def test_the_baseline_is_reviewer_ready_at_any_future_instant(
    as_of: str | None, regenerate: bool, tmp_path: Path
):
    """The baseline must be reviewer-ready whenever someone arrives.

    Authority declarations previously carried a reviewer-specific expiry, so the
    tree started failing with APPROVAL_EXPIRED - a diagnostic that is not about a
    missing approval - once that date passed. They now carry the non-expiring
    representation, so that failure cannot return.

    Machine evidence is a different matter and this test is deliberately split
    to say so. Nornyx has no non-expiring representation for it, so it carries a
    real finite window and the guarantee is regeneration, not permanence. An
    earlier version of this test asserted permanence and passed only because a
    2099 sentinel made "expired" look far away. See
    docs/governance/EVIDENCE_FRESHNESS.md.
    """
    command = [sys.executable, SCRIPT, "--as-of", as_of or _inside_committed_window()]
    if regenerate:
        command.append("--regenerate")
    completed = subprocess.run(
        command,
        cwd=_tree(tmp_path),
        capture_output=True,
        text=True,
    )
    assert completed.returncode == 0, completed.stdout + completed.stderr
    report = json.loads(completed.stdout)
    assert report["status"] == "pass"
    assert report["human_approval_present"] is False
    for contract in report["contracts"]:
        assert contract["approval_blocked"] is True, contract
        assert contract["unexpected_diagnostics"] == [], contract


@pytest.mark.skipif(shutil.which("nornyx") is None, reason="nornyx CLI is not installed")
def test_no_approval_is_inferred_or_generated(tmp_path: Path):
    """Regenerating evidence must never bring an approval into existence."""
    workspace = _tree(tmp_path)
    evidence = workspace / CONTRACTS / "evidence"
    assert not list(evidence.glob("*human_approval*")), "an approval artifact exists"
    report = json.loads(
        subprocess.run(
            [sys.executable, SCRIPT], cwd=workspace, capture_output=True, text=True
        ).stdout
    )
    assert report["human_approval_present"] is False


@pytest.mark.skipif(shutil.which("nornyx") is None, reason="nornyx CLI is not installed")
def test_baseline_fails_on_a_non_approval_defect(tmp_path: Path):
    """A stale revision is a defect, not an approval gap, so it must fail.

    Without this the gate would pass any broken contract that also happened to
    be missing its approval record.
    """
    workspace = _tree(tmp_path)
    contract = workspace / CONTRACTS / "runtime_network.nyx"
    contract.write_text(
        contract.read_text(encoding="utf-8").replace(
            "subject_revision: git:", "subject_revision: git:dead", 1
        ),
        encoding="utf-8",
    )

    completed = _run(workspace)
    assert completed.returncode == 2, completed.stdout + completed.stderr
    report = json.loads(completed.stdout)
    assert report["status"] == "fail"
    offending = [
        item for entry in report["contracts"] for item in entry["unexpected_diagnostics"]
    ]
    assert offending, report
