"""Temporal enforcement of a human approval, proven without needing a real one.

The fixture below synthesizes a clearly-labelled TEST approval inside a throwaway
copy of the contracts. It is never committed as evidence and never presented as
a real approval; it exists so the absent, valid, expired, and not-yet-valid
states can all be driven against the real Nornyx gate on a branch that carries no
human approval of its own.
"""

from __future__ import annotations

import hashlib
import json
import shutil
import subprocess
from pathlib import Path

import pytest
import yaml

ROOT = Path(__file__).resolve().parents[1]
CONTRACTS = Path(".nornyx/contracts")
RUNTIME = "runtime_network.nyx"

FIXTURE_STATEMENT = (
    "SYNTHETIC TEST FIXTURE - NOT A REAL APPROVAL. Generated by the test suite "
    "to drive Nornyx temporal validation. It grants nothing and represents no "
    "human decision."
)


def _tree(tmp_path: Path) -> Path:
    workspace = tmp_path / "repo"
    workspace.mkdir()
    shutil.copytree(ROOT / CONTRACTS, workspace / CONTRACTS)
    return workspace


def _install_fixture_approval(workspace: Path, *, generated_at: str, expires_at: str) -> None:
    """Add a synthetic approval record to the copied runtime contract."""
    path = workspace / CONTRACTS / RUNTIME
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    # Read the governed revision from the contract rather than pinning it, so
    # the fixture keeps working as the baseline is rebound.
    revision = document["governance_evidence"]["subject_revision"]
    payload = {
        "schema": "nornyx.forge.human_approval_record.v1",
        "approval": "granted",
        "producer": {"id": "human.test_fixture:network_governance_owner", "type": "human"},
        "status": "pass",
        "subject_revision": revision,
        "generated_at": generated_at,
        "expires_at": expires_at,
        "statement": FIXTURE_STATEMENT,
    }
    raw = json.dumps(payload, indent=2, sort_keys=True).encode("utf-8") + b"\n"
    artifact = workspace / CONTRACTS / "evidence" / "fixture_approval.json"
    artifact.write_bytes(raw)

    path = workspace / CONTRACTS / RUNTIME
    document = yaml.safe_load(path.read_text(encoding="utf-8"))
    document["governance_evidence"]["records"].append(
        {
            "id": "approval_record",
            "type": "approval_record",
            "schema_id": "nornyx.governance_evidence.v1",
            "producer": payload["producer"],
            "artifact": "evidence/fixture_approval.json",
            "content_hash": "sha256:" + hashlib.sha256(raw).hexdigest(),
            "subject_revision": revision,
            "tool": {"name": "test_fixture", "version": "1"},
            "generated_at": generated_at,
            "expires_at": expires_at,
            "status": "pass",
            "dependencies": [],
        }
    )
    for approval in document["approvals"]:
        if approval["name"] == "agentic_network_authority":
            approval["expires_at"] = expires_at
    path.write_text(yaml.safe_dump(document, sort_keys=False), encoding="utf-8")


def _check(workspace: Path, *, as_of: str) -> tuple[int, str]:
    completed = subprocess.run(
        [
            shutil.which("nornyx") or "nornyx",
            "check",
            str(workspace / CONTRACTS / RUNTIME),
            "--as-of",
            as_of,
        ],
        cwd=workspace,
        capture_output=True,
        text=True,
    )
    return completed.returncode, completed.stdout + completed.stderr


needs_nornyx = pytest.mark.skipif(
    shutil.which("nornyx") is None, reason="nornyx CLI is not installed"
)


@needs_nornyx
def test_absent_approval_blocks_the_contract(tmp_path: Path):
    """With no approval at all the contract must not validate."""
    code, output = _check(_tree(tmp_path), as_of="2026-08-03T00:00:00Z")
    assert code != 0
    assert "APPROVAL" in output


@needs_nornyx
def test_approval_validates_inside_its_window(tmp_path: Path):
    """A valid, in-window approval is what makes the contract pass.

    Without this the expiry tests below could pass for the wrong reason - a
    contract that never validates is trivially "closed".
    """
    workspace = _tree(tmp_path)
    _install_fixture_approval(
        workspace,
        generated_at="2026-08-02T00:00:00Z",
        expires_at="2026-08-05T00:00:00Z",
    )
    code, output = _check(workspace, as_of="2026-08-03T00:00:00Z")
    assert code == 0, output


@needs_nornyx
def test_approval_stops_working_after_it_expires(tmp_path: Path):
    """The same approval, evaluated past its window, must close the contract."""
    workspace = _tree(tmp_path)
    _install_fixture_approval(
        workspace,
        generated_at="2026-08-02T00:00:00Z",
        expires_at="2026-08-05T00:00:00Z",
    )
    code, output = _check(workspace, as_of="2026-08-06T00:00:00Z")
    assert code != 0, "an expired approval still validated"
    assert "EXPIRED" in output or "STALE" in output, output


@needs_nornyx
def test_approval_does_not_cover_earlier_events(tmp_path: Path):
    """An approval cannot authorize anything that happened before it existed."""
    workspace = _tree(tmp_path)
    _install_fixture_approval(
        workspace,
        generated_at="2026-08-02T00:00:00Z",
        expires_at="2026-08-05T00:00:00Z",
    )
    code, output = _check(workspace, as_of="2026-08-01T00:00:00Z")
    assert code != 0, "approval validated before it was issued"
    assert "NOT_YET_VALID" in output or "FUTURE" in output, output


@needs_nornyx
def test_window_wider_than_the_module_cap_is_refused(tmp_path: Path):
    """The seven-day cap is enforced, so a long window cannot be self-granted."""
    workspace = _tree(tmp_path)
    _install_fixture_approval(
        workspace,
        generated_at="2026-08-02T00:00:00Z",
        expires_at="2026-12-31T00:00:00Z",
    )
    code, output = _check(workspace, as_of="2026-08-03T00:00:00Z")
    assert code != 0, "an over-long approval window was accepted"
    assert "EXCESSIVE" in output or "EXPIRY" in output, output
